Add logging
voicevox-client/python pull request #13
Opened 2023-03-16 07:09 UTC by tuna2134

2023-03-17 22:26 UTC, tasuren requested changes

2023-03-17 22:26 UTC, tasuren commented on voicevox/http.py
> +        logger.debug("Stop session")
過去形じゃないから、`aclose`する前にこれ置けば？

2023-03-17 22:26 UTC, tasuren commented on voicevox/http.py
> +            logger.debug(response.content)
ここらへんのログを全部`.debug`でまとめて`response = await self.session ...`の下に置かない？
そしたら、これからエラーが増えた時にいちいち書かなくて済むし、loggerを標準出力に出すようにしてたときに、`.error`と`raise`で二重にエラーが出なくて済む。

2023-03-17 23:29 UTC, tuna2134 commented on voicevox/http.py
> +        logger.debug("Stop session")
Ok

2023-03-17 23:30 UTC, tuna2134 commented on voicevox/http.py
> +            logger.debug(response.content)
そうだね

2023-03-17 23:51 UTC, tasuren requested changes

2023-03-17 23:51 UTC, tasuren commented on voicevox/http.py
> +        logger.debug(response.content)
`method`と`path`もやった方がわかりやすいかも。
後、ステータスコードとか。
リクエストする前にリクエストのログを`Request: {method}: {path}: {kwargs}`みたいにして、リクエスト後にレスポンスのログを`Response: {0.status_code}: {0.content}`みたいにすれば。

2023-03-18 00:26 UTC, tasuren submitted a review, later dismissed

2023-03-18 00:40 UTC, tasuren commented on voicevox/http.py
>          logger.debug(f"Response: {response.content}")
ステータスコードもあった方がいいんじゃない。
```suggestion
        logger.debug("Response: {0.status_code}: {0.content}".format(response))
```

2023-03-18 00:59 UTC, tuna2134 commented on voicevox/http.py
>          logger.debug(f"Response: {response.content}")
せやな

2023-03-18 01:14 UTC, tasuren approved these changes

2023-03-18 01:19 UTC, merged